name: CD action to push changes
on:
  push:
env:
  UPDATE_HOST: "${{ secrets.UPDATE_HOST }}"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-cloud-runner
    steps:
      - uses: actions/checkout@v4
      - name: Push changes
        run: python3 scripts/deploy.py